version: '2'
services:
  rancher-rebalancer:
    image: scentregroup/rancher-rebalancer
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.agent.role: environment
      io.rancher.container.create_agent: 'true'
      io.rancher.container.pull_image: always
